system:
  root: "/storage/projects/CTU_Speech_Lab"
  scratch: "/storage/projects/CTU_Speech_Lab/scratch/varhavit"
  workspace: "/storage/projects/CTU_Speech_Lab/workspace/varhavit"

paths:
  sph2pipe: "tools/sph2pipe/sph2pipe"
  clean_data:
    - "data/WSJ/wsj1_CDset/disk1/wsj1/si_tr_s"
  noise_data:
    - "data/additive_noises/QUT_NOISES/CAFE_FOODCOURTB_1"
    - "data/additive_noises/QUT_NOISES/HOME_KITCHEN_1"
    - "data/additive_noises/QUT_NOISES/CAFE_CAFE_1"
    - "data/additive_noises/QUT_NOISES/CAR_WINCLOSED_1"
  manifest_dir: "manifest"
  train_manifest: "manifest/train_mini.csv"
  eval_manifest: "manifest/train_mini.csv"
  dnsmos_model: "models/dnsmos_model.onnx"
  save_dir: "/auto/projects-du-praha/CTU_Speech_Lab/workspace/varhavit/speech-enhancement-cmgan/checkpoints"

audio:
  sample_rate: 16000
  n_fft: 400
  hop_length: 100
  segment_seconds: 2.0
  target_snr: [-5, 0, 5, 10, 15, 20, 30, 40]

training:
  batch_size: 16
  num_workers: 4
  pin_memory: true
  loss_weights: [0.1, 0.9, 0.2, 0.05]
  epochs: 16
  decay_epoch: 4
  init_lr: 5e-4

model:
  num_channel: 64

evaluation:
  batch_limit: 5
